@baseUrl = http://localhost:8080
@token = PEGAR_JWT_AQUI

############################################################
# Auth Controller (ruta: /api/auth)
# Requiere: NO (register/login)
############################################################

### Registrar usuario
# Response example: ../JsonResponses/auth/register.200.json
# Response example (400): ../JsonResponses/auth/register.400.json
POST {{baseUrl}}/api/auth/register
Content-Type: application/json

{
  "username": "admin",
  "password": "1234",
  "role": "Admin"
}

### Login (obtiene JWT)
# Response example: ../JsonResponses/auth/login.200.json
# Response example (401): ../JsonResponses/auth/login.401.json
POST {{baseUrl}}/api/auth/login
Content-Type: application/json

{
  "username": "admin",
  "password": "1234"
}
